#!/usr/bin/python -Wall

# ==============================================================================
# Prints pseudorandom numbers uniformly distributed within a specified range.
# John Kerl 2011-11-03
# ==============================================================================

import random
import sys

# ------------------------------------------------------------------------------
def usage():
	print >> sys.stderr, "Usage: %s {lo} {hi} {count}"
	print >> sys.stderr, \
		"Prints {count} pseudo-random integers x with lo <= x < hi."
	print >> sys.stderr, "lo must be < hi, and count must be > 0."
	sys.exit(1)

# ------------------------------------------------------------------------------
if len(sys.argv) != 4:
	usage()
lo    = 0
hi    = 0
count = 0
try:
	lo    = int(sys.argv[1])
	hi    = int(sys.argv[2])
	count = int(sys.argv[3])
except:
	usage()
if lo >= hi:
	usage()
if count < 1:
	usage()
pyhi = hi-1 # Python's random module uses inclusive-upper convention.

for i in xrange(0, count):
	print random.randint(lo, pyhi)
