#!/usr/bin/python -Wall

# Knuth shuffle
# John Kerl
# 2012-02-29

import sys, random

N = 5
reps = 100
if len(sys.argv) == 2:
	N = int(sys.argv[1])
if len(sys.argv) == 3:
	N = int(sys.argv[1])
	reps = int(sys.argv[2])

x = [0] * N
for i in xrange(0, N):
	x[i] = i

# Permute the numbers 0..N-1.  Then, print them out 1..N.
for k in xrange(0, reps):

	for i in xrange(0, N-1):
		j    = random.randint(i, N-1)
		t    = x[i]
		x[i] = x[j]
		x[j] = t

	for i in xrange(0, N):
		print x[i]+1,
	print
