#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 {branch to rebase from, e.g. main" 1>&2
  echo "Idea is to bring a local branch up to date with remote head."
  exit 1
fi

git pull --rebase=interactive origin "$1"
