#!/bin/bash

# ================================================================
# This is a minimal script meant to set up access to the scripts in this
# directory tree.  It should be invoked via
#
#   eval $(/path/to/this/file)
#
# in order to have effect on the calling shell's PATH variable.
#
# ================================================================
# The tools in this package are meant for two purposes: (1) day-in-day-out use
# in my home directory on a few familiar machines; (2) drop-in use on machines
# I don't regularly visit. The intent of this package in the latter is to make
# myself at home, and productive, as quickly as possible: a suitcase, or a
# toolbox. What makes a house a home?  A home environment consists of (at
# least) executables; aliases; PATH; PS1; various environment variables (e.g.
# $vlp=/very/long/path/goes/here/so/I/need/not/type/it/each/time); and editor
# setup.  Moreover, items in my suitcase fall into two categories: (a) always
# useful; (b) per-project useful. The aux directory is for the latter.
#
# ================================================================
# Sample use of this script:
#
# ----------------------------------------------------------------
# Suitcase setup on the home machine:
#
#   # Set up always-useful things
#   rm -rf ./scripts
#   git clone http://github.com/johnkerl/scripts
#   rm -rf ./scripts/.git # Prune for quicker scp
#
#   # Add in per-project useful things
#   cp something-or-other scripts/aux
#   cp somedir/*          scripts/aux
#   echo "export vlp= /very/long/path/goes/here/so/I/need/not/type/it/each/time" >> scripts/aux/rc
#   echo 'alias  vlp="cd $vlp; "'  >> scripts/aux/rc
#
# ----------------------------------------------------------------
# Shipping the suitcase:
#
#   scp -C -r scripts user@away-machine.domain.name:/path/over/there/scripts
#
# ----------------------------------------------------------------
# Suitcase unpack on the away machine:
#
#   eval $(/path/over/there/scripts/rc)
#
# ================================================================
# John Kerl 2013-10-04
# ================================================================

ourdir=$(dirname $0)
# Absolutize
if [ "$ourdir" = "." ]; then
    ourdir=$(pwd)
elif [ "${ourdir:0:1}" != "/" ]; then
    ourdir="$(pwd)/$ourdir";
fi

echo "export PATH=$ourdir/abbrevs:\$PATH;"  # Keystroke-savers: like aliases, but they work from within vim subshells.
echo "export PATH=$ourdir/arith:\$PATH;"    # Column-sum etc.
echo "export PATH=$ourdir/fundam:\$PATH;"   # Essentials
echo "export PATH=$ourdir/aux:\$PATH;"      # Per-project executables can be dropped in here.

echo "alias vim='vim -u $ourdir/minrc/vimrc';" # Editor setup
echo ". $ourdir/minrc/aliases;"             # Aliases
echo ". $ourdir/minrc/promptrc;"            # PS1
echo ". $ourdir/aux/rc"                     # Per-project aliases/variables can be dropped in here.
