#!/bin/bash

# ================================================================
# Please see ./suitcase/README.md for context.
#
# This is a minimal script meant to set up access to the scripts in this
# directory tree.  It should be invoked via
#
#   eval $(/path/to/this/file)
#
# in order to have effect on the calling shell's PATH variable.
#
# ================================================================
# John Kerl 2013-10-04
# ================================================================

ourdir=$(dirname $0)
# Absolutize
if [ "$ourdir" = "." ]; then
    ourdir=$(pwd)
elif [ "${ourdir:0:1}" != "/" ]; then
    ourdir="$(pwd)/$ourdir";
fi

echo "export PATH=$ourdir/abbrevs:\$PATH;"  # Keystroke-savers: like aliases, but they work from within vim subshells.
echo "export PATH=$ourdir/arith:\$PATH;"    # Column-sum etc.
echo "export PATH=$ourdir/fundam:\$PATH;"   # Essentials
echo "export PATH=$ourdir/aux:\$PATH;"      # Per-project executables can be dropped in here.

echo "alias vim='vim -u $ourdir/minrc/vimrc';" # Editor setup
echo ". $ourdir/minrc/aliases;"             # Aliases
echo ". $ourdir/minrc/promptrc;"            # PS1
echo ". $ourdir/aux/rc"                     # Per-project aliases/variables can be dropped in here.
