#!/usr/bin/env ruby

# Changes Esperanto ĉ into cx, etc. -- particularly useful since these
# circumflex letters aren't available on all keyboards. See also the sibling
# eox2d script.
#
# Case-preservation:
# * 'ĉu vi iris?' maps to 'cxu vi iris?'
# * 'Ĉu vi iras?' maps to 'Cxu vi iras?'
# * 'ĈU VI IROS?' maps to 'CXU VI IROS?'

ARGF.each do |line|
  line = line.
    gsub(/ĉ/, 'cx').
    gsub(/ĝ/, 'gx').
    gsub(/ĥ/, 'hx').
    gsub(/ĵ/, 'jx').
    gsub(/ŝ/, 'sx').
    gsub(/ŭ/, 'ux')

  if line =~ /Ĉ([A-Z])/
    line.gsub!(/Ĉ([A-Z])/, "CX"+$1)
  end
  if line =~ /Ĝ([A-Z])/
    line.gsub!(/Ĝ([A-Z])/, "GX"+$1)
  end
  if line =~ /Ĥ([A-Z])/
    line.gsub!(/Ĥ([A-Z])/, "HX"+$1)
  end
  if line =~ /Ĵ([A-Z])/
    line.gsub!(/Ĵ([A-Z])/, "JX"+$1)
  end
  if line =~ /Ŝ([A-Z])/
    line.gsub!(/Ŝ([A-Z])/, "SX"+$1)
  end
  if line =~ /Ŭ([A-Z])/
    line.gsub!(/Ŭ([A-Z])/, "UX"+$1)
  end

  line = line.
    gsub(/Ĉ/, 'Cx').
    gsub(/Ĝ/, 'Gx').
    gsub(/Ĥ/, 'Hx').
    gsub(/Ĵ/, 'Jx').
    gsub(/Ŝ/, 'Sx').
    gsub(/Ŭ/, 'Ux')

  puts line
end
