#!/usr/bin/env python

# ================================================================
# John Kerl
# kerl.john.r@gmail.com
# 2020-08-09
# xxx retype
# Prints {count} words of {length} characters each, with characters selected
# uniformly randomly from uppercase A-Z, lowercase a-z, and 0-9.
# ================================================================

import sys
import random

# ----------------------------------------------------------------
def usage(exit_code):
    o = sys.stdout if exit_code == 0 else sys.stderr
    o.write("Usage: %s {count} {choices}\n" % (sys.argv[0]))
    sys.exit(exit_code)

# ----------------------------------------------------------------
# xxx use getopt
count = 1

argc = len(sys.argv)
if argc < 2:
    usage(1)
elif sys.argv[1] == '-h':
    usage(0)
elif sys.argv[1] == '--help':
    usage(0)

if argc < 3:
    usage(1)

count = int(sys.argv[1])
choices = sys.argv[2:]

for i in range(0, count):
    print(random.choices(choices)[0])
