#!/usr/bin/env python

import os, sys, getopt, random

default_n     = 1
default_mu    = 0.0
default_sigma = 1.0

# ----------------------------------------------------------------
def usage():
    print >> sys.stderr, "Usage: %s {-n n} {-m mu} {-s sigma}" % os.path.basename(sys.argv[0])
    print >> sys.stderr, "Generates normally distributed pseudorandom floating-point numbers."
    print >> sys.stderr, "n defaults to %d." % (default_n)
    print >> sys.stderr, "mu defaults to %lf." % (default_mu)
    print >> sys.stderr, "sigma defaults to %lf." % (default_sigma)

# ----------------------------------------------------------------
n     = default_n
mu    = default_mu
sigma = default_sigma

try:
  optargs, non_option_args = getopt.getopt(sys.argv[1:], "hn:m:s:", ['help'])
except getopt.GetoptError, err:
  print str(err)
  usage()
  sys.exit(1)

for opt, arg in optargs:
  if opt == '-h' or opt == '--help':
    usage()
    sys.exit(0)
  elif opt == '-n':
    n = int(arg)
  elif opt == '-m':
    mu = float(arg)
  elif opt == '-s':
    sigma = float(arg)
  else:
    print >> sys.stderr, "Unhandled option \"%s\"." % opt
    sys.exit(1)

non_option_arg_count = len(non_option_args)
if non_option_arg_count != 0:
  usage()
  sys.exit(0)

for n in xrange(0, n):
    u = random.normalvariate(mu, sigma)
    print u
