#!/usr/bin/env python

# ================================================================
# John Kerl
# kerl.john.r@gmail.com
# 2020-08-09
# xxx retype
# Prints {count} words of {length} characters each, with characters selected
# uniformly randomly from uppercase A-Z, lowercase a-z, and 0-9.
# ================================================================

import sys
import random

# ----------------------------------------------------------------
def usage(exit_code):
    o = sys.stdout if exit_code == 0 else sys.stderr
    o.write("Usage: %s {choices} [length [count]]\n" % (sys.argv[0]))
    sys.exit(exit_code)

# ----------------------------------------------------------------
length  = 16
count   = 1

argc = len(sys.argv)
if argc< 2:
    usage(1)
elif sys.argv[1] == '-h':
    usage(0)
elif sys.argv[1] == '--help':
    usage(0)
choices = sys.argv[1]

if argc == 3:
    length = int(sys.argv[2])
elif argc == 4:
    length = int(sys.argv[2])
    count  = int(sys.argv[3])

for i in range(0, count):
    word = ""
    for j in range(0, length):
         word += random.choice(choices)
    print(word)
