#!/usr/bin/perl

# Prints the average of numbers in an input stream, one number per line.
# E.g. with input
#   1
#   2
#   3
#   4
#   5
# output is
#   3

$sum = 0;
$count = 0;

if (@ARGV) {
	for my $num (@ARGV) {
		$sum += $num;
		$count++;
	}
}
else {
	while ($line=<>) {
		chomp $line;
		my @nums = split /\s+/, $line;
		for my $num (@nums) {
			$sum += $num;
			$count++;
		}
	}
}

if ($count == 0) {
	print "empty\n";
}
else {
	print $sum/$count, "\n";
}
