#!/usr/bin/perl
$| = 1; # for tail -f contexts

# ================================================================
# Prints the cumulative (running) sum of numbers in an input stream, one number
# per line.  E.g. with input
#   1
#   2
#   3
#   4
#   5
# output is
#   1
#   3
#   6
#   10
#   15
# ================================================================

$sum = 0.0;
$paste_line_right = 0;
if (scalar(@ARGV) > 0 && $ARGV[0] eq '-r') {
  $paste_line_right = 1;
  shift @ARGV;
}
while ($line = <>) {
   chomp $line;

   # Strip leading whitespace from line.
   $line =~ s/^\s+//;

   # Get only the first token on the line.
   ($f) = split /\s+/, $line;

   # Skip blank lines.
   next if ($f =~ m/^[ \t]*$/);

   # Accumulate sum.
   $sum += $f;
   if ($paste_line_right) {
     print "$sum\t$line\n";
   } else {
     print "$sum\n";
   }
}
