#!/usr/bin/perl

# ================================================================
# Prints the cumulative (running) sum of numbers in an input stream, one number
# per line.  E.g. with input
#   1
#   2
#   3
#   4
#   5
# output is
#   1
#   3
#   6
#   10
#   15
# ================================================================

$sum = 0.0;
while ($line = <>) {
   chomp $line;

   # Strip leading whitespace from line.
   $line =~ s/^\s+//;

   # Get only the first token on the line.
   ($f) = split /\s+/, $line;

   # Skip blank lines.
   next if ($f =~ m/^[ \t]*$/);

   # Accumulate sum.
   $sum += $f;
   print "$sum\n";
}
