#!/usr/bin/perl
use line_term_lib;

$sum = 0.0;
while ($line = <>) {
	($line, $term) = split_line_ending($line);

	# Strip leading whitespace from line.
	$line =~ s/^\s+//;

	# Get only the first token on the line.
	($f) = split /\s+/, $line;

	# Skip blank lines.
	next if ($f =~ m/^[ \t]*$/);

	# Accumulate sum.
	$sum += $f;
}
print "$sum$term";
