#!/usr/bin/env python

import sys
import math

if len(sys.argv) != 3:
    print("Usage: {k1} {k2}", file=sys.stderr)
    sys.exit(1)

k1 = int(sys.argv[1])
k2 = int(sys.argv[2])

n = k1 + k2

k1 + k1 - k1 -k2

z = (k1 - k2) / math.sqrt(n)

print(f"{z: .4f}")
