#!/usr/bin/env ruby
# Simple base-64 encoder
require 'base64'
if ARGV.length == 0
  # Ruby readline chomps newlines for us
  $stdin.readlines.each do |line|
    puts Base64.encode64 line
  end
else
  ARGV.each do |arg|
     puts Base64.encode64 arg
  end
end
