#! /bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Makes a backup copy of each file named on the command line.
# ================================================================

if [ $# -lt 1 ]; then
	echo "Usage:  `basename $0` {file names to back up}" 1>&2
	exit 1
fi

for fn
do
	cp $fn ${fn}.bak && chmod u+w ${fn}.bak
done
