#!/usr/bin/python -Wall

# ================================================================
# John Kerl
# 2012-09-12
# ================================================================

import random

for i in xrange(0, 30):
	s = ""
	for j in xrange(0, 78):
		s += random.choice(".*o@")
	print s
		
