#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints a carriage return after the nth line.
# ================================================================

die "Usage: $0 {n} [input]\n" unless @ARGV;
$n = shift @ARGV;

$i = 0;
while ($line = <>) {
   chomp $line;
   $i++;
   print "$line\n";
   if ($i == $n) {
      print "\n";
   }
}
