#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints a carriage return after the ith line.
# ================================================================

use line_term_lib;
die "Usage: $0 {n} [input]\n" unless @ARGV;
$n = shift @ARGV;

$i = 0;
while ($line = <>) {
	($line, $term) = split_line_ending($line);
	$i++;
	print "$line$term";
	if ($i == $n) {
		print "$term";
	}
}
