#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints a carriage return before lines matching a specified pattern.
# ================================================================

die "Usage: $0 {pattern} [input]\n" unless @ARGV;
$pattern = shift @ARGV;

while ($line = <>) {
   $line.chomp;
   if ($line =~ m/$pattern/) {
      print "\n";
   }
   print "$line";
}
