#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints a carriage return before lines matching a specified pattern.
# ================================================================

use line_term_lib;
die "Usage: $0 {pattern} [input]\n" unless @ARGV;
$pattern = shift @ARGV;

while ($line = <>) {
	($line, $term) = split_line_ending($line);
	if ($line =~ m/$pattern/) {
		print "$term";
	}
	print "$line$term";
}
