#!/usr/bin/env ruby
$stdout.sync = true

# ==============================================================================
# John Kerl
# http://johnkerl.org
# 2013-08-10
#
# Given input of the form
#   1
#   2
#   3
#   4
#   5
# produces output of the form
#   1 2
#   2 3
#   3 4
#   4 5
#   5
# ==============================================================================

currline = nil
nextline = nil
while true
	begin
		nextline = $stdin.readline
	rescue EOFError
		break
	end
	nextline.chomp!
	unless currline.nil?
		pair = currline + " " + nextline
		puts pair.rstrip
	end
	currline = nextline
end
#puts nextline unless nextline.nil?
