#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints dashes below a header line, e.g.
#   a b c
#   1 2 3
# goes to
#   a b c
#   - - -
#   1 2 3
# ================================================================

$lno = 0;
while ($line = <>) {
   chomp $line;
   $lno++;
   chomp $line;
   print "$line\n";
   if ($lno == 1) {
      $iscom = 0;
      $iscom = 1 if ($line =~ m/^#/);
      $line =~ s/[^ \t]/-/g;
      $line =~ s/^./#/ if ($iscom);
      print "$line\n";
   }
}
