#!/usr/bin/env ruby

# ================================================================
# Converts RFC8601 date string to seconds since the epoch.
# John Kerl, 2013
# ================================================================

require 'time'

$us = File.basename $0

# ----------------------------------------------------------------
def usage()
   $stderr.puts "Usage: #{$us} {one or more RFC8601 date strings, e.g. 2013-06-03T17:02:34Z}"
   exit 1
end

# ----------------------------------------------------------------
def main()
   usage unless ARGV.length > 0
   ok = true
   for arg in ARGV
      seconds = 0
      begin
         puts Time.parse(arg).to_i
      rescue ArgumentError => e
         $stderr.puts "#{$us} can't parse \"#{arg}\" as RFC8601."
         ok = false
      end
   end
   if ok
      exit 0
   else
      exit 1
   end
end

# ----------------------------------------------------------------
main()
