#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Renames files, replacing uppercase characters with lowercase.
# From my NT days.
# ================================================================

if [ $# -eq 0 ]; then
	echo "Usage: $0 {filenames ...}" 1>&2
fi

scriptdir="$(dirname "$0")"

for oldname; do
	newname="`echo "$oldname" | "$scriptdir/downcase"`"
	if [ "$oldname" != "$newname" ]; then
		mv "$oldname" "$newname"
	fi
done
