#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Renames files, replacing uppercase characters with lowercase.
# From my NT days.
# ================================================================

if [ $# -eq 0 ]; then
	echo "Usage: $0 {filenames ...}" 1>&2
fi

for oldname; do
	newname="`echo $oldname | tr [A-Z] [a-z]`"
	if [ $oldname != $newname ]; then
		mv "$oldname" "$newname"
	fi
done
