#! /bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Detach and run a program, with no bg/fg strings attached.
# ================================================================

$* &
