#!/usr/bin/ruby

# ================================================================
# John Kerl
# http://johnkerl.org
# Double-spaces the input.
# ================================================================

ARGF.each do |line|
	puts
	puts line
end
