#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# This is simply date, with my favorite format args.
# ================================================================

TZ="America/New_York" date  "+%a %b %d %Y %H:%M:%S %Z"  # 24-hour clock
