#!/usr/bin/env python

# ================================================================
# John Kerl
# 2010-03-27
# kerl.john.r@gmail.com
# Prints an array of numbers in the specified input stream
# as a nice columnar matrix.
# ================================================================

from __future__ import division # 1/2 = 0.5, not 0.
import sys
import tabutil_m

format    = '%11.7f'
file_name = '-'

argc = len(sys.argv)
if argc == 1:
	pass
elif argc == 2:
	format    = sys.argv[1]
elif argc == 3:
	format    = sys.argv[1]
	file_name = sys.argv[2]
else:
	sys.stderr.write("Usage: %s {format [file name]}\n" % (sys.argv[0]))
	sys.stderr.write("Use \"-\" as file name, or omit, to read from stdin.\n")
	sys.exit(1)

columns = tabutil_m.float_columns_from_file(file_name)
tabutil_m.float_columns_to_file(columns, '-', format)
