#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints lines after a specfied pattern, e.g. "START OF DUMP" or some such.
# Useful for log-snarfing.
# ================================================================

die "Usage: $0 {begin-pattern} [input]\n" unless @ARGV >= 1;
$begin_pattern = shift @ARGV;

$in = 0;
while ($line = <>) {
	if ($line =~ m/$begin_pattern/) {
		$in = 1;
	} elsif ($in) {
		print "$line";
	}
}
