#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# A vim filter for left-alignment.
# ================================================================

exec colprint -l "$@"
