#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Sorts lines by length.
# ================================================================

$do_reverse = 0;
if (@ARGV > 0) {
  if ($ARGV[0] eq "-r") {
    $do_reverse = 1;
    shift @ARGV;
  }
}

if ($do_reverse) {
  @lines = sort lensort_reverse <>;
} else {
  @lines = sort lensort <>;
}
for my $line (@lines) {
	print $line;
}

# ----------------------------------------------------------------
sub lensort
{
	my $la = length($a);
	my $lb = length($b);
	if ($la == $lb) {
		return $a cmp $b;
	}
	else {
		return $la - $lb;
	}
}

# ----------------------------------------------------------------
sub lensort_reverse
{
	my $la = length($a);
	my $lb = length($b);
	if ($la == $lb) {
		return $a cmp $b;
	}
	else {
		return $lb - $la;
	}
}
