#!/bin/bash

# Reorders input lines stably sorted (i.e. partitioned) by having/not-having specified pattern
export pattern="$1"
shift
set -x
mlr --nidx --fs '\001' put -q -S '
  if ($1 =~ ENV["pattern"]) {
    @with[NR] = $*;
  } else {
    @without[NR] = $*;
  }
  end {
    emit @with;
    emit @without;
  }
' "$@"
