#!/usr/bin/perl -Wall
use line_term_lib;

# ================================================================
# John Kerl
# http://johnkerl.org
# Sorts words within each input line.
# E.g. input
#   Sorts words within each input line.
# maps to output
#   Sorts each input line. within words
# ================================================================

$numeric = 0;
if ((@ARGV > 0) && ($ARGV[0]) eq "-n") {
	$numeric = 1;
	shift @ARGV;
}
while ($line=<>) {
	($line, $term) = split_line_ending($line);
	$line =~ s/^\s+//;
	$line =~ s/\s+$//;
	@fields = split /\s+/, $line;
	if ($numeric) {
		@fields = sort {$a <=> $b} @fields;
	}
	else {
		@fields = sort @fields;
	}
	$i = 0;
	for my $field (@fields) {
		if ($i > 0) {
			printf " ";
		}
		printf $field;
		$i++;
	}
	printf "$term";
}
