#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# A vim filter for text alignment.  See colprint.
# ================================================================

exec colprint -lr $@
