#!/bin/bash

# ================================================================
# John Kerl
# http://johnkerl.org
# A filter to strip leading and trailing whitespace.
# ================================================================

if [ $(uname) == Darwin ]; then
   sed -E -e 's/^[[:space:]]+//' -e 's/[[:space:]]+$//'
else
   sed -r -e 's/^\s+//' -e 's/\s+$//'
fi
