#! /bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Recursive ls, e.g. lsr \*.java.
# ================================================================

set -o noglob

names=
for arg
do
	if [ -z "$names" ]; then
		names="-name $arg"
	else
		names="$names -o -name $arg"
	fi
done

find . -follow $names
