#! /bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Recursive ls, e.g. lsr \*.java.
# ================================================================

set -o noglob

types=""
names=
for arg
do
  if [ "$arg" = "-f" ]; then
    types="-type f"
  elif [ "$arg" = "-d" ]; then
    types="-type d"
	elif [ -z "$names" ]; then
		names="-name $arg"
	else
		names="$names -o -name $arg"
	fi
done

find . $types -follow $names
