#!/usr/bin/ruby

require 'time'

@@us = File.basename $0

# ----------------------------------------------------------------
def usage()
	$stderr.puts "Usage: #{@@us} {one or more numbers}"
	$stderr.puts "Prints the numbers divided by 2^20. See also mega."
	exit 1
end

# ----------------------------------------------------------------
def main()
	usage unless ARGV.length > 0
	ok = true
	for arg in ARGV
		begin
			n = Float(arg)
			g = n / 2**20
			if g.abs < 0.1
			   puts g
			else
				puts "%.3f" % g
			end
		rescue ArgumentError => e
			$stderr.puts "#{@@us} can't parse \"#{arg}\" as float."
			ok = false
		end
	end
	if ok
		exit 0
	else
		exit 1
	end
end

# ----------------------------------------------------------------
main()
