#! /bin/sh

me=`basename $0`
if [ $# -ge 1 ]; then
  pattern=$1; shift
	files=$@
else
  echo "$me:  Usage -- $me pat, where pat is a regexp." 1>&2
  exit 1
fi

awk 'BEGIN{FS="\n";RS="";ORS="\n\n"} ! /'"$pattern"'/ {print}' $files
