#! /bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# A keystroke-saver.  E.g. ls -l | nf is much like ls -1.
# ================================================================

awk '{print $NF}' $@
