#!/usr/bin/perl

# ----------------------------------------------------------------
# John Kerl
# john.kerl@avnet.com
# 2000/12/18
#
# Removes blank lines from the input stream.
# ----------------------------------------------------------------

while ($line = <>) {
   chomp $line;
   next if ($line =~ m/^\s*$/);
   print $line;
   print "\n";
}
