#!/usr/bin/env ruby

# Given a sequence of paragraphs, sorts the paragraphs lexically

longest_first = true
if ARGV.length >= 1 && ARGV[0] == '-r'
  longest_first = false
  ARGV.shift
end

paragraphs = []
ARGF.each("\n\n") do |paragraph|
   paragraphs << paragraph
end

paragraphs.sort!

puts paragraphs.join("\n")
