#!/bin/bash

# Reorders input paragraphs stably sorted (i.e. partitioned) by having/not-having specified pattern
pattern="$1"
shift
mlr --nidx --rs '\n\n' --fs '\001' put -q -S '
  if ($1 =~ "'$pattern'") {
    @with[NR] = $*;
  } else {
    @without[NR] = $*;
  }
  end {
    emit @with;
    emit @without;
  }
' "$@"
