#!/usr/bin/env ruby

# Ingests paragraphs, sorts them by line count, and prints them out

longest_first = true
if ARGV.length >= 1 && ARGV[0] == '-r'
  longest_first = false
  ARGV.shift
end

paragraphs = []
ARGF.each("\n\n") do |paragraph|
   paragraphs << paragraph.split("\n")
end

if longest_first
  paragraphs.sort!{|a,b| b.length <=> a.length}
else
  paragraphs.sort!{|a,b| a.length <=> b.length}
end

at_first = true
paragraphs.each do |paragraph|
   puts unless at_first
   at_first = false
   paragraph.each do |line|
      puts line
   end
end
