#!/usr/bin/perl -w

use line_term_lib;
$input = "";

while ($line = <>) {
	($line, $term) = split_line_ending($line);

	# Get line ending and remember it ...
	chomp $line;

	# ... then print with that line ending.

	if ($line =~ m/^>/) {
		if ($input ne "") {
			print "$input$term";
		}
		$input = "";
		print "$line$term";
	}
	elsif ($line =~ m/^\s*$/) {
		$input =~ s/\s$//;
		print "$input$term";
		print "$term";
		$input = "";
	}
	else {
		$input .= $line;
		$input .= " ";
	}
}

if ($input ne "") {
	print "$input$term";
}
