#!/usr/bin/perl -w

# ================================================================
# John Kerl
# http://johnkerl.org
# Flows paragraphs without line breaks.  Useful for e.g.
# confluence wiki editing.
# ================================================================

$input = "";

while ($line = <>) {
   chomp $line;

   if ($line =~ m/^>/) {
      if ($input ne "") {
         print "$input\n";
      }
      $input = "";
      print "$line\n";
   }
   elsif ($line =~ m/^\s*$/) {
      $input =~ s/\s$//;
      print "$input\n";
      print "\n";
      $input = "";
   }
   else {
      $input .= $line;
      $input .= " ";
   }
}

if ($input ne "") {
   print "$input\n";
}
