#!/usr/bin/perl -w

# ================================================================
# John Kerl
# http://johnkerl.org
# Flows paragraphs without line breaks.  Useful for e.g.
# confluence wiki editing.
# ================================================================

use line_term_lib;
$input = "";

while ($line = <>) {
	($line, $term) = split_line_ending($line);

	chomp $line;

	if ($line =~ m/^>/) {
		if ($input ne "") {
			print "$input$term";
		}
		$input = "";
		print "$line$term";
	}
	elsif ($line =~ m/^\s*$/) {
		$input =~ s/\s$//;
		print "$input$term";
		print "$term";
		$input = "";
	}
	else {
		$input .= $line;
		$input .= " ";
	}
}

if ($input ne "") {
	print "$input$term";
}
