#!/usr/bin/env python

import sys

if len(sys.argv) < 2:
    print("Usage: %s {string} {zero or more file names}", file=sys.stderr)
    sys.exit(1)
prefix = sys.argv[1]
args = sys.argv[2:]

if len(args) == 0:
    while True:
        line = sys.stdin.readline()
        if line == '':
            break
        line = line.rstrip()
        print(prefix + line)
else:
    for filename in args:
            mode = 'r'
            try:
                file_handle = open(filename, mode)
            except:
                sys.stderr.write("%s: couldn't open file \"%s\" for mode \"%s\".\n" % (sys.argv[0], filename, mode))
                sys.exit(1)
            while True:
                line = file_handle.readline()
                if line == '':
                    break
                line = line.rstrip()
                print(prefix + line)
            file_handle.close()
