#!/usr/bin/perl -w

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints each line three times, carriage-return delimited.  Occasionally useful
# as a text-editing technique.
# ================================================================

while ($line = <>) {
   chomp $line;
   print "$line\n";
   print "$line\n";
   print "$line\n";
}
