#!/usr/bin/perl -w

# ================================================================
# John Kerl
# http://johnkerl.org
# Prints each line three times, space-delimited.  Occasionally useful
# as a text-editing technique.
# ================================================================

while ($line = <>) {
   chomp $line;
   print "$line $line $line\n";
}
