#!/usr/bin/env python -i

from __future__ import division
import os, sys, getopt, random
from math import *

if len(sys.argv) >= 2:
	string = str.join(' ', sys.argv[1:])
	print eval(string)
	#sys.exit(0)
	os._exit(0)
else:
	pass
	# Take further stuff from the '>>> ' prompt
