#!/bin/bash

ourdir=$(dirname $0)
if [ $# -ge 1 ] ; then
	#rlwrap python $ourdir/py-from-args "$@"
	python $ourdir/py-from-args "$@"
else
	#rlwrap python -i $ourdir/py-from-interp
	python -i $ourdir/py-from-interp
fi
