#!/usr/bin/env python

# ================================================================
# See ./py for context
# ================================================================

import os, sys, getopt, random, time
from math import *

pass
# Take further stuff from the '>>> ' prompt
