#!/usr/bin/env python

# ================================================================
# See ./py for context
# ================================================================

import os, sys, getopt, random, time
from math import *
import tiledb, tiledb.cloud, tiledbsc

if len(sys.argv) < 2:
    sys.stderr.write("Usage: %s {expression}\n" % sys.argv[0])
    sys.exit(1) 

string = str.join(' ', sys.argv[1:])
print((eval(string)))
