#!/usr/bin/env python

# ================================================================
# See ./pyw for context
# ================================================================

import os, sys, getopt, random, time, math

import tiledb, tiledb.cloud
import tiledbsc as t
import anndata  as ad
import numpy    as np
import pandas   as pd
import pyarrow  as pa
import scanpy   as sc
import scipy    as sp

print('tiledb.__version__       ', tiledb.__version__)
print('core version             ', ".".join(str(ijk) for ijk in list(tiledb.libtiledb.version())))
print('tiledb.cloud.__version__ ', tiledb.cloud.__version__)
print('anndata.__version__  (ad)', ad.__version__)
print('numpy.__version__    (np)', np.__version__)
print('pandas.__version__   (pd)', pd.__version__)
print('pyarrow.__version__  (pa)', pa.__version__)
print('scanpy.__version__   (sc)', sc.__version__)
print('scipy.__version__    (sp)', sp.__version__)

# ----------------------------------------------------------------
import readline
def history(n=10):
    history_length = readline.get_current_history_length()
    history_range = range(history_length - n, history_length)
    lines = [str(readline.get_history_item(i + 1)) for i in history_range]
    print('\n'.join(lines))
# ----------------------------------------------------------------

pass
# Take further stuff from the '>>> ' prompt
