#!/usr/bin/env python

# ================================================================
# See ./pytt for context
# ================================================================

import os, sys, getopt, random, time, math

import tiledb
import tiledbsoma
import tiledbsoma.io
soma = tiledbsoma
try:
    import tiledbsoma.libtiledbsoma as clib
except ModuleNotFoundError:
    pass

import numpy   as np
import pandas  as pd
import pyarrow as pa
import anndata as ad
import scanpy  as sc
import scipy   as sp

print('tiledbsoma.__version__   ', tiledbsoma.__version__)
print('tiledb.__version__       ', tiledb.__version__)
print('core version             ', ".".join(str(ijk) for ijk in list(tiledb.libtiledb.version())))
print('anndata.__version__  (ad)', ad.__version__)
print('numpy.__version__    (np)', np.__version__)
print('pandas.__version__   (pd)', pd.__version__)
print('pyarrow.__version__  (pa)', pa.__version__)
print('scanpy.__version__   (sc)', sc.__version__)
print('scipy.__version__    (sp)', sp.__version__)
print('python__version__        ', ".".join([str(e) for e in [sys.version_info.major, sys.version_info.minor, sys.version_info.micro]]))

# ----------------------------------------------------------------
import readline
def history(n=10):
    history_length = readline.get_current_history_length()
    history_range = range(history_length - n, history_length)
    lines = [str(readline.get_history_item(i + 1)) for i in history_range]
    print('\n'.join(lines))
# ----------------------------------------------------------------


pass
# Take further stuff from the '>>> ' prompt
