#!/usr/bin/env python

# ================================================================
# See ./pyw for context
# ================================================================

import os, sys, getopt, random, time, math

import tiledb, tiledb.cloud, tiledbsc
import anndata as ad
import numpy   as np
import pandas  as pd

print('tiledb.__version__       ', tiledb.__version__)
print('tiledb.cloud.__version__ ', tiledb.cloud.__version__)
print('anndata.__version__  (ad)', ad.__version__)
print('numpy.__version__    (np)', np.__version__)
print('pandas.__version__   (pd)', pd.__version__)

pass
# Take further stuff from the '>>> ' prompt
