#!/usr/bin/env python

from __future__ import division
import os, sys, getopt, random
from math import *

if len(sys.argv) < 2:
	print >> sys.stderr, "Usage: %s {expression}" % sys.argv[0]
	sys.exit(1)
string = str.join(' ', sys.argv[1:])
print eval(string)
