#!/bin/bash

# ================================================================
# Same as ./py but with auto-load of tiledb
# ================================================================

ourdir=$(dirname $0)
if [ "$1" = "-z" ]; then
    python    $ourdir/pyt.py
else
    python -i $ourdir/pyt.py
fi
