#!/bin/bash

# ================================================================
# Same as ./py but with auto-load of tiledb
# ================================================================

ourdir=$(dirname $0)
if [ -z "$DYLD_LIBRARY_PATH" ]; then
    export DYLD_LIBRARY_PATH="/usr/local/lib"
fi
if [ -z "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH="/usr/local/lib"
fi
if [ "$1" = "-z" ]; then
    python    $ourdir/pytt.py
else
    python -i $ourdir/pytt.py
fi
