#!/bin/bash

# ================================================================
# Same as ./py but with auto-load of tiledb
# ================================================================

ourdir=$(dirname $0)
if [ "$1" = "-z" ]; then
    python    $ourdir/py-from-interp-import-tiledb-and-cloud-and-tiledbsoma
else
    python -i $ourdir/py-from-interp-import-tiledb-and-cloud-and-tiledbsoma
fi
