#!/usr/bin/env python

import os, sys, getopt, random, typing

default_n     = 1
default_mu    = 0.0
default_sigma = 1.0

# ----------------------------------------------------------------
def usage() -> None:
    sys.stderr.write("Usage: %s {-n n} {-m mu} {-s sigma}\n" % os.path.basename(sys.argv[0]))
    sys.stderr.write("Generates normally distributed pseudorandom floating-point numbers.\n")
    sys.stderr.write("n defaults to %d.\n" % (default_n))
    sys.stderr.write("mu defaults to %lf.\n" % (default_mu))
    sys.stderr.write("sigma defaults to %lf.\n" % (default_sigma))

# ----------------------------------------------------------------
n     = default_n
mu    = default_mu
sigma = default_sigma

try:
    optargs, non_option_args = getopt.getopt(sys.argv[1:], "hn:m:s:", ['help'])
except getopt.GetoptError as err:
    print((str(err)))
    usage()
    sys.exit(1)

for opt, arg in optargs:
    if opt == '-h' or opt == '--help':
        usage()
        sys.exit(0)
    elif opt == '-n':
        n = int(arg)
    elif opt == '-m':
        mu = float(arg)
    elif opt == '-s':
        sigma = float(arg)
    else:
        sys.stderr.write("Unhandled option \"%s\".\n" % opt)
        sys.exit(1)

non_option_arg_count = len(non_option_args)
if non_option_arg_count != 0:
    usage()
    sys.exit(0)

for n in range(0, n):
    u = random.normalvariate(mu, sigma)
    print(u)
