#!/usr/bin/perl -w

# ================================================================
# John Kerl
# http://johnkerl.org
# Reverses the order of input lines.
# It turns out that in Linux there is now the "tac" command.
# ================================================================

@lines = <>;
$n = scalar @lines;
for ($i = $n-1; $i >= 0; $i--) {
	$line = $lines[$i];
	chomp $line;
	print "$line\n";
}
