#!/usr/bin/perl
use line_term_lib;

# ----------------------------------------------------------------
# John Kerl
# john.kerl@avnet.com
# 2000/12/18
#
# Removes blank lines.
# ----------------------------------------------------------------

while ($line = <>) {
	($line, $term) = split_line_ending($line);
	next if ($line =~ m/^\s*$/);
	print $line;
	print "$term";
}
