#!/usr/bin/python -Wall

import sys, os, time

us = os.path.basename(sys.argv[0])

# ----------------------------------------------------------------
def usage():
	print >> sys.stderr, \
		"Usage: %s {one or more integers counting seconds since the epoch}" % us
	sys.exit(1)

# ----------------------------------------------------------------
def main():
	ok = True
	if len(sys.argv) < 2:
		usage()
	for arg in sys.argv[1:]:
		seconds = 0
		try:
			seconds = int(arg)
		except:
			print >> sys.stderr, "%s: can't parse \"%s\" as integer." % (us, arg)
			ok = False
			continue
		t = time.gmtime(seconds)
		s = time.strftime("%Y%m%d %H:%M:%S %z", t)
		print s
	if ok:
		sys.exit(0)
	else:
		sys.exit(1)

# ----------------------------------------------------------------
main()
