#!/bin/bash

us=$(basename $0)
if [ $# -ne 1 ]; then
  echo "Usage: $us {dir}" 1>&2
  exit 1
fi
dir="$1"
port=9999

logdir="$HOME/tmp"
mkdir -p "$logdir"

if lsof -iTCP:$port -sTCP:LISTEN >/dev/null 2>&1; then
  echo "$us: port $port is already in use" 1>&2
  exit 1
fi

echo "Serving on localhost:$port"
nohup npx http-server "$dir" -o -p $port > "$logdir/nohup.out" 2>&1 &
