#!/usr/bin/ruby

# ----------------------------------------------------------------
# John Kerl
# john.kerl@avnet.com
# 2000/12/18
# Ported to Ruby 2013-08-20
# Strips empty lines from the input stream.
# ----------------------------------------------------------------

ARGF.each do |line|
	line.chomp!
	puts line unless line =~ /^\s*$/
end
