#!/bin/bash

# ================================================================
# John Kerl
# http://johnkerl.org
# A filter to strip trailing whitespace.
# ================================================================

if [ $(uname) == Darwin ]; then
   sed -E 's/[[:space:]]+$//'
else
   sed -r 's/\s+$//'
fi
