#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Date with LaTeX formatting.
# ================================================================

if [ "$#" -eq 1 ]; then
    export TZ="$1"
    if [ "$TZ" = "ny" ]; then export TZ="America/New_York"; fi
    if [ "$TZ" = "NY" ]; then export TZ="America/New_York"; fi
fi

echo "\\emph{`date +%c`}"
