#!/bin/bash

if [ $# -lt 1 ]; then
	#echo "Usage: $(basename $0) {title text here}." 1>&2
	#exit 1
	text="Terminal"
else
    text="$@"
fi

if [ "$(uname)" = "Darwin" ]; then
  starttitle=$'\033]0;'
  endtitle=$'\007'
else
  starttitle="\e]2;"
  endtitle="\a"
fi

# xxx cmt re mac ...
#echo -e $starttitle '[[' $text ']]' $endtitle
echo -e $starttitle $text $endtitle
