#!/usr/bin/perl -w

# ================================================================
# John Kerl
# kerl.john.r@gmail.com
# 2006-05-26
# Like repeated Jj in vim: e.g.
#
# $ jot 1 10
#   1
#   2
#   3
#   4
#   5
#   6
#   7
#   8
#   9
#   10
#
# $ jot 1 10 | twoper
#   1 2
#   3 4
#   5 6
#   7 8
#   9 10
# ================================================================

$parity = 0;
while ($line = <>) {
    chomp $line;
    print $line;
    if ($parity) {
        print "\n";
    }
    else {
        print " ";
    }
    $parity = !$parity;
}
if ($parity) {
    print "\n";
}
