#! /bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Makes specified files unwritable.
# ================================================================

if [ $# -lt 1 ]; then
	echo "Usage: $0 {one or more files ... }" 1>&2
fi

for arg
do
	if [ ! -e $arg ]; then
		touch $arg
	fi
	chmod u-w $arg
done
