#!/usr/bin/perl -w

# ================================================================
# John Kerl
# http://johnkerl.org
# Undoes creach.
# ================================================================

die "Usage: $0 {n} [input]\n" unless @ARGV;
$n = shift @ARGV;

$i = 0;
while ($line = <>) {
   chomp $line;
   $i++;
   print "$line";
   if ($i == $n) {
      print "\n";
      $i = 0;
   }
   else {
      print " ";
   }
}
