#!/usr/bin/perl

# ================================================================
# John Kerl
# http://johnkerl.org
# Uppercasing filter.
# ================================================================

use open ':std', ':encoding(UTF-8)';
use feature 'unicode_strings';

while (<>) {
	print uc;
}
