#!/usr/bin/env ruby

# ================================================================
# John Kerl
# http://johnkerl.org
# UTC date
# ================================================================

fmt = '%Y-%m-%dT%H:%M:%S'
t = Time.now.utc
if ARGV.length == 0
  puts t.strftime fmt
elsif ARGV.length == 1
  t = t + Float(ARGV[0])
  puts t.strftime fmt
else
  $stderr.puts "b04k"
  exit 1
end
