#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# UTC date
# ================================================================
us=$(basename $0)

if [ $# -eq 0 ]; then
   date -u "+%Y-%m-%dT%H:%M:%SZ"
elif [ $# -eq 1 ]; then
   date -d "$1 seconds ago" -u "+%Y-%m-%dT%H:%M:%SZ"
else
   echo "Usage: $us [seconds ago]" 1>&2
   exit 1
fi

