#!/usr/bin/env python

# ================================================================
# Renames files to have a date-stamp prefix.
# ================================================================

import sys
import os
import re
import datetime

# ----------------------------------------------------------------
def usage():
    sys.stderr.write("Usage: %s \{one or more file names}\n" % sys.argv[0])

# ----------------------------------------------------------------
def neaten_name(name: str) -> str:
    # Idempotence
    if re.match("^20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]-", name):
        return name

    name = name.rstrip('/')
    dirn = os.path.dirname(name)
    base = os.path.basename(name)

    now = datetime.datetime.now()
    formatted = now.strftime("%Y-%m-%d")

    base = formatted + "-" + base
    return os.path.join(dirn, base)

# ----------------------------------------------------------------
if len(sys.argv) < 2:
    usage()
for name in sys.argv[1:]:
    new_name = neaten_name(name)
    if new_name != name:
        os.rename(name, new_name)
        print(new_name)
