#!/bin/sh

# ================================================================
# John Kerl
# http://johnkerl.org
# Touches a file and makes it executable.  First thing I type
# when creating a new script (followed by vim).
# ================================================================

#date "+%Y-%m-%d-%H:%M:%S"
date "+%Y%m%d-%H%M%S"
