#!/usr/bin/perl -Wall

# ================================================================
# John Kerl
# http://johnkerl.org
# Cats out a file in the $PATH.
# ================================================================

while ($line=<>) {
   chomp $line;
   #$line = lc($line);
   $line =~ s/[\.,;:\*_?!'"\[\]()]//g;
   @words = split /\s+/, $line;
   next unless $line =~ m/[a-zA-Z]/;
   for my $word (@words) {
      next unless $word =~ m/[a-zA-Z]/;
      #print "$word";
      $counts{$word}++;
   }
}

for my $key (sort keys %counts) {
   printf "%7d %s\n", $counts{$key}, $key;
}
