#!/usr/bin/perl -w

@lines=<>;
$maxcols = 0;
$numrows = 0;

for ($i = 0; $i < @lines; $i++) {
	$line = $lines[$i];
 	chomp $line;
 	$line =~ s/^\s+//;
 	$line =~ s/\s+$//;
	next if $line =~ m/^$/;
 	my @fields = split /\s+/, $line;
 	$maxcols = @fields if @fields > $maxcols;
 	for ($j = 0; $j < @fields; $j++) {
 		$$matrix[$numrows][$j] = $fields[$j];
 	}
	$numrows++;
}

for ($j = 0; $j < $maxcols; $j++) {
	for ($i = 0; $i < $numrows; $i++) {
		print " " if ($i > 0);
		print $$matrix[$i][$j];
	}
	print "\n";
}
