#!/usr/bin/python -Wall

# ================================================================
# John Kerl
# 2007-06-28
# kerl.john.r@gmail.com
# Computes autocorrelation of series, which are columnar data
# in an input stream.
# ================================================================

from __future__ import division # 1/2 = 0.5, not 0.
import sys
import tabutil_m
import stats_m

# ----------------------------------------------------------------
def usage():
	print >> sys.stderr, "Usage: %s {x file name} [numk]" % (sys.argv[0])
	print >> sys.stderr, "Use \"-\" as file name for stdin."
	sys.exit(1)

# ----------------------------------------------------------------
argc = len(sys.argv)
if argc == 1:
	file_name = '-'
	farrays = tabutil_m.float_columns_from_file(file_name)
	numk = len(farrays[0])
elif argc == 2:
	if sys.argv[1] == '-h':
		usage()
	if sys.argv[1] == '--help':
		usage()
	file_name = sys.argv[1]
	farrays = tabutil_m.float_columns_from_file(file_name)
	numk = len(farrays[0])
elif argc == 3:
	file_name = sys.argv[1]
	farrays = tabutil_m.float_columns_from_file(file_name)
	numk = int(sys.argv[2])
else:
	usage()

autocorrs = []
for farray in farrays:
	autocorr = stats_m.find_sample_autocorr(farray, numk)
	autocorrs.append(autocorr)
tabutil_m.float_columns_to_file(autocorrs, '-')
