#!/usr/bin/python -Wall

# ================================================================
# John Kerl
# 2007-06-28
# kerl.john.r@gmail.com
# ================================================================
# This software is released under the terms of the GNU GPL.
# Please see LICENSE.txt in the same directory as this file.
# ================================================================

from __future__ import division # 1/2 = 0.5, not 0.
import sys
import sackmat_m
import pyrcio_m
import stats_m

argc = len(sys.argv)
if (argc != 2):
	print >> sys.stderr, "Usage: %s {file name}." % (sys.argv[0])
	print >> sys.stderr, "Use \"-\" as file name for stdin."
	print >> sys.stderr, "Each line of the file should contain one whitespace-delimited tuple."
	sys.exit(1)
file_name = sys.argv[1]

# ----------------------------------------------------------------
xs = pyrcio_m.read_real_matrix(file_name)
Q = stats_m.find_sample_correlation_matrix(xs)
#Q.printf()
print Q
