#!/usr/bin/python -Wall

# ================================================================
# John Kerl
# 2007-06-28
# kerl.john.r@gmail.com
# ================================================================

from __future__ import division # 1/2 = 0.5, not 0.
import sys
import sackmat_m
import stats_m

# ----------------------------------------------------------------
def usage():
	print >> sys.stderr, "Usage: %s {file name}" % (sys.argv[0])
	print >> sys.stderr, "Use \"-\" as file name to read from standard input."
	sys.exit(1)

# ----------------------------------------------------------------
# Parse the command line.
argi = 1
argc = len(sys.argv)
while ((argi < argc) and (sys.argv[argi][0] == '-')):
	if (sys.argv[argi] == '-'):
		break
	elif (sys.argv[argi] == '--'):
		break
	elif (sys.argv[argi] == '--help'):
		usage()
	elif (sys.argv[argi] == '-h'):
		usage()
	else:
		usage()
	argi += 1

if (argc - argi) == 0:
	file_name = '-'
elif (argc - argi) == 1:
	file_name = sys.argv[argi]
else:
	usage()

# ----------------------------------------------------------------
iarray = sackmat_m.read_column_vector(int, file_name)
lo = stats_m.find_min(iarray)
hi = stats_m.find_max(iarray)
counts = [0] * (hi-lo+1)

for x in iarray:
	counts[x-lo] += 1
for x in range(lo, hi+1):
	print x, counts[x-lo]
