#!/usr/bin/python -Wall

# ================================================================
# John Kerl
# 2007-06-28
# kerl.john.r@gmail.com
# ================================================================

from __future__ import division # 1/2 = 0.5, not 0.
import sys
import sackmat_m
import tabutil_m
import stats_m

argc = len(sys.argv)
if (argc != 3):
	print >> sys.stderr, "Usage: %s {X file name} {y file name}" \
		% (sys.argv[0])
	print >> sys.stderr, \
	"The X file should be n lines, each with p whitespace-delimited numbers."
	print >> sys.stderr, \
	"The y file should be n lines, each with one number."
	print >> sys.stderr, \
	"Then n is the number of samples and p is the number of regressors."
	print >> sys.stderr, "Use \"-\" as file name for stdin."
	sys.exit(1)

X = sackmat_m.read_matrix(float, sys.argv[1])
y = tabutil_m.float_columns_from_file(sys.argv[2])[0]

ols_info = stats_m.compute_ols(X, y)
print ols_info
