#!/usr/bin/python -Wall

# ================================================================
# John Kerl
# 2007-06-28
# kerl.john.r@gmail.com
# ================================================================

from __future__ import division # 1/2 = 0.5, not 0.
import sys
import tabutil_m
import stats_m

argc = len(sys.argv)
if argc == 1:
	file_names = ['-']
elif argc >= 2:
	file_names = sys.argv[1:]
else:
	print >> sys.stderr, "Usage: %s {one or more file names}" % (sys.argv[0])
	print >> sys.stderr, "Use \"-\" to read from stdin."
	sys.exit(1)

for file_name in file_names:
	farrays = tabutil_m.float_columns_from_file(file_name)

	for farray in farrays:
		sorted_distro = stats_m.find_sorted_distro(farray)
		tabutil_m.float_columns_to_file(sorted_distro, '-')
