#!/usr/bin/ruby

@@us = File.basename $0

# ================================================================
# John Kerl
# http://johnkerl.org
# 2013-08-19
#
# Sorts CSKV fields by key. Useful for homogenizing multiple CSKV lines which
# were printed using different hash-map orderings. E.g. input
#
#   a=1,b=2,c=3
#   b=5,c=6,a=4
#
# maps to output
#
#   a=1,b=2,c=3
#   a=4,b=5,c=6
# ================================================================

ARGF.each do |line|
    puts line.chomp.split(/,/).sort.join(',')
end
