#!/bin/bash

# ==============================================================================
# John Kerl
# 2012-03-25
#
# Sorts CSV data by a given column name.  Just a thin wrapper around the system
# sort program.
#
# ----------------------------------------------------------------
# Examples:
#
# $ cat mydata.txt
# a,b,c
# 1,2,3
# 14,5,6
# 7,8,9
#
# $ csort +a mydata.txt
# a,b,c
# 1,2,3
# 14,5,6
# 7,8,9
#
# $ csort --numeric +a mydata.txt
# a,b,c
# 1,2,3
# 7,8,9
# 14,5,6
# ==============================================================================

us=$(basename $0)

# ------------------------------------------------------------------------------
usage() {
    echo "Usage: $us  {column} [table]" 1>&2
    echo "Or:    $us +{column} [table]" 1>&2
    echo "Or:    $us -{column} [table]" 1>&2
    echo "Sorts a CSV table by a specified column.  If table name is omitted," 1>&2
    echo "standard input is read.  Use +, or no prefix, for ascending; - for descending." 1>&2
    echo "Precede column name with --numeric to do numeric sort." 1>&2
    exit 1
}

# ------------------------------------------------------------------------------
# Parse the command line.
numeric=""
if [ "$1" = "--numeric" ]; then
    numeric="-n "
    shift
fi
if [ $# -eq 1 ]; then
    sort_column="$1"
    table="-"
elif [ $# -eq 2 ]; then
    sort_column="$1"
    table="$2"
else
    usage
fi

direction="up"
if [ "${sort_column:0:1}" = "+" ]; then
    sort_column=${sort_column#+}
elif [ "${sort_column:0:1}" = "-" ]; then
    sort_column=${sort_column#-}
    direction="down"
fi

# ------------------------------------------------------------------------------
# Read the header so that we can map column name to column number.
if [ "$table" = "-" ]; then
    read header
else
    header=$(head -1 $table)
fi
columns=$(echo $header | sed 's/,/ /g')
i=1
colnum="undef"
for column in $columns; do
    if [ "$column" = "$sort_column" ]; then
        colnum=$i
    fi
    i=$[i+1]
done
if [ "$colnum" = "undef" ]; then
    echo "$us:  Can't find column named \"$sort_column\" in table \"$table\" with header \"$header\"." 1>&2
    exit 1
fi

# Map our command-line arguments to the arguments to the system sort program.
if [ "$direction" = "up" ]; then
    sort_args="${numeric}-t, -k $colnum"
else
    sort_args="${numeric}-t, -k $colnum -r"
fi

# ------------------------------------------------------------------------------
# Write the CSV header as-is.
echo $header

# ------------------------------------------------------------------------------
# Do the sort of everything after the header.
if [ "$table" = "-" ]; then
    # The header line has been read from stdin.  Pass the rest off to sort.
    exec sort $sort_args
else
    sed 1d $table | sort $sort_args
fi
