#!/usr/bin/ruby

# ================================================================
# We convert from JKV to JKH format as follows:
# * split on whitespace
# * print transposed
# * left-justify all output columns (which were input rows)
# * print dashes line
#
# Please see format-notes.txt in this directory for more information.
#
# John Kerl, 2012-03-31
# ================================================================

@@us     = File.basename($0)
@@ourdir = File.dirname($0)

require 'getoptlong'

# ================================================================
def main()
	$decode_whitespace = false
	$encode_whitespace = false

	getopt = GetoptLong.new(
		[ '-d', '--decode', GetoptLong::NO_ARGUMENT ],
		[ '-e', '--encode', GetoptLong::NO_ARGUMENT ],
		[ '-h', '--head',   GetoptLong::REQUIRED_ARGUMENT ]
	)
	getopt.each do |opt, arg|
		case opt
			when "-d";
				$decode_whitespace = true
			when "-e";
				$encode_whitespace = true
		end
	end
	filenames = ARGV

	ok = true
	if filenames.length == 0
		ok &= do_stdin()
	else
		filenames.each{|filename| ok &= do_file(filename)}
	end
end

# ----------------------------------------------------------------
def line_to_fields(input_line)
	fields = input_line.chomp.split(/\s+/)
	if $decode_whitespace
		fields.collect{|field| field.gsub(/%20/, ' ').gsub(/%09/, '\t')}
	else
		fields
	end
end

# ----------------------------------------------------------------
# Non-streaming, since we need to read all lines to find the maximum column
# widths.
def do_stdin()
	do_lines($stdin.readlines)
	return true
end

# ----------------------------------------------------------------
# Non-streaming, since we need to read all lines to find the maximum column
# widths.
def do_file(filename)
	if ! File.exists?(filename)
		$stderr.puts "Can't find \"#{filename}\"."
		return false
	end
	do_lines(File.readlines(filename))
	return true
end

# ----------------------------------------------------------------
def do_lines(lines)

	# Read, split, and store lines, finding maximum field width for each input
	# row (output column).
	fields_list = []
	max_num_cols = 0
	row_max_widths = {}
	row_number = 0
	lines.each_with_index do |input_line, line_number|

		fields = line_to_fields(input_line)
		fields_list << fields
		if $encode_whitespace
			fields.collect{|field| field.gsub(/ /, '%20').gsub(/\t/, '%09')}
		end
		max_num_cols = [max_num_cols, fields.length].max
		row_max_widths[row_number] = fields.collect{|field|field.length}.max
		row_number += 1
	end
	num_rows = row_number

	# Print transposed

	for j in (0..(max_num_cols-1)) do
		transposed_fields = []
		for i in (0..(num_rows-1)) do
			cell = fields_list[i][j]
			cell = "" if cell.nil?
			transposed_fields << cell.ljust(row_max_widths[i])
		end

		# Add the dashes line
		if j == 1
			puts transposed_fields.collect{|field|
				field.gsub(/./, '-')
			}.join(' ')
		end

		# Data
		puts transposed_fields.join(' ')
	end

	return true
end

# ================================================================
# Top-down programming style, please.
main()
